BottomNavigationBar Component 작업 완료
MentalJava/sym-mvvm-clone pull request #14
Opened 2024-12-17 10:31 UTC by MentalJava

2024-12-17 12:57 UTC, kdjun97 commented
@MentalJava 
conflict 나는것 같은데 확인 부탁드립니다.

2024-12-17 12:58 UTC, kdjun97 commented on lib/ui/component/s_navigation.dart
> +        child: BottomNavigationBar(
@MentalJava 
onTap의 위치를 다시 한 번 생각해보시면 좋을 것 같습니다.

2024-12-17 12:58 UTC, kdjun97 commented
@MentalJava 
영상은 확인했는데, 혹시 각각의 탭을 눌렀을 때, 화면이 바뀌는 것 까지 시험해보셨을까요?

2024-12-17 12:59 UTC, kdjun97 requested changes
@MentalJava 
PR comment 달았습니다.
확인 부탁드립니다!

2024-12-18 17:00 UTC, MentalJava commented on lib/ui/component/s_navigation.dart
> +        child: BottomNavigationBar(
다시 수정해서 commit 완료 했습니다.

2024-12-19 05:37 UTC, kdjun97 requested changes
@MentalJava 
conflict 다시 확인좀요

2024-12-21 15:47 UTC, kdjun97 approved these changes
@MentalJava 고생하셨습니다!

2024-12-21 15:47 UTC, merged